# See https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on: [pull_request]
permissions:
  contents: read
jobs:
  dependency-review:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Security Review
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: low
          allow-licenses: MIT
  dependency-updates:
    name: Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Versions Review
        run: |
          # error off since we use 'git diff' to determine changes
          set +o errexit
          go get -u all; go mod tidy
          set -o errexit
          TMP_GIT_STATUS_GO_MOD=$(git diff go.mod)
          echo "TMP_GIT_STATUS_GO_MOD=${TMP_GIT_STATUS_GO_MOD}"

          if [ "${TMP_GIT_STATUS_GO_MOD}" == "" ]; then
            echo '::warning title=Foo::Dependencies are NOT outdated'

            else
              echo '::warning title=Bar::Dependencies are outdated'
          fi
