# See https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on: [pull_request]
permissions:
  checks: write
  contents: write
env:
  BX_PR_NUMBER: ${{ github.event.number }}
jobs:
  dependency-review:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Security Review
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: low
          allow-licenses: MIT
  dependency-updates:
    name: Versions
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Versions Review
        run: |
          echo "::notice ::BX_PR_NUMBER=${BX_PR_NUMBER}"

          # error off since we use 'git diff' to determine changes
          set +o errexit
          echo "::group::Downloading dependencies"
          go get -u all; go mod tidy
          echo "::endgroup::"
          set -o errexit

          TMP_GIT_STATUS_GO_MOD=$(git diff go.mod)
          echo "::debug ::TMP_GIT_STATUS_GO_MOD=${TMP_GIT_STATUS_GO_MOD}"

          if [ "${TMP_GIT_STATUS_GO_MOD}" == "" ]; then
            echo "::warning ::Dependencies are NOT outdated"
            echo "::group::Adding PR comment"
            curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${BX_PR_NUMBER}/comments -d "{\"body\":\"WARNING - Dependencies are outdated\", \"commit_id\":\"${GITHUB_SHA}\"}"
            echo "::endgroup::"
            echo "::group::Updating PR"
            curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/check-runs -d "{\"name\":\"Dependencies are outdated\", \"head_sha\":\"${GITHUB_SHA}\",\"conclusion\":\"action_required\"}"
            echo "::endgroup::"

            else
              echo "::warning ::Dependencies are outdated"
              echo "::group::Adding PR comment"
              curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${BX_PR_NUMBER}/comments -d "{\"body\":\"WARNING - Dependencies are outdated\", \"commit_id\":\"${GITHUB_SHA}\"}"
              echo "::endgroup::"
              echo "::group::Updating PR"
              curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/check-runs -d "{\"name\":\"Dependencies are outdated\", \"head_sha\":\"${GITHUB_SHA}\",\"conclusion\":\"action_required\"}"
              echo "::endgroup::"
          fi
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: 'Thank you for the PR!'
            });
