# See https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on: [pull_request]
permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write
env:
  BX_PR_NUMBER: ${{ github.event.number }}
jobs:
  dependency-review:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Security Review
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: low
          allow-licenses: MIT
  dependency-updates:
    name: Versions
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Versions Review
        id: dependency_versions_review
        run: |
          echo "::notice ::BX_PR_NUMBER=${BX_PR_NUMBER}"

          # error off since we use 'git diff' to determine changes
          set +o errexit
          echo "::group::Downloading dependencies"
          go get -u all; go mod tidy
          echo "::endgroup::"
          set -o errexit

          TMP_GIT_STATUS_GO_MOD=$(git diff go.mod)
          echo "::debug ::TMP_GIT_STATUS_GO_MOD=${TMP_GIT_STATUS_GO_MOD}"

          if [ "${TMP_GIT_STATUS_GO_MOD}" == "" ]; then
            echo "::warning ::Dependencies are NOT outdated"

            echo "::group::Updating PR"
            curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/check-runs -d "{\"actions\":[{\"label\":\"Foo\",\"description\":\"Bar\",\"identifier\":\"Baz\"}],\"name\":\"Dependencies are outdated\", \"head_sha\":\"${GITHUB_SHA}\",\"conclusion\":\"action_required\"}"
            echo "::endgroup::"

            echo "::set-output name=dependencies_outdated::true"

            else
              echo "::warning ::Dependencies are outdated"

              echo "::group::Updating PR"
              curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/check-runs -d "{\"actions\":[{\"label\":\"Foo\",\"description\":\"Bar\",\"identifier\":\"Baz\"}],\"name\":\"Dependencies are outdated\", \"head_sha\":\"${GITHUB_SHA}\",\"conclusion\":\"action_required\"}"
              echo "::endgroup::"

              echo "::set-output name=dependencies_outdated::true"
          fi
        shell: bash
      - name: Add Comment to PR
        if: ${{ steps.dependency_versions_review.outputs.dependencies_outdated == 'true' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            //console.log("GITHUB_API_URL=", process.env.GITHUB_API_URL)
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "🔴 DEPENDENCIES OUTDATED 🔴"
            })

            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["🔴 DEPENDENCIES OUTDATED 🔴"]
            })

            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: process.env.BX_PR_NUMBER,
              event: "COMMENT",
              comments: [{"path":"go.mod","position":1,"body":"🔴 DEPENDENCIES OUTDATED 🔴"}]
            })
